<?php

namespace App\ORM;

use SilverStripe\ORM\DataList;
use SilverStripe\ORM\DataObject;

class ManyManyEagerLoader extends EagerLoader
{
    /**
     * @return DataList
     */
    protected function createList()
    {
        $this->list = $this->parentList->relation($this->relationName);

        return $this;
    }

    /**
     * @return string
     */
    public function getRelationClass()
    {
        $result = $this->schema->manyManyComponent($this->parentDataObjectClass, $this->relationName);

        return $result['relationClass'];
    }

    /**
     * @return $this|void
     */
    public function createMap()
    {
        // TODO: Implement createMap() method.
    }

    /**
     * @param DataObject $dataObject
     * @return DataObject|void
     */
    public function extract(DataObject $dataObject)
    {
        // TODO: Implement extract() method.
    }

    /**
     * @param DataObject $dataObject
     */
    public function applyToDataObject(DataObject $dataObject)
    {
        parent::applyToDataObject($dataObject); // TODO: Change the autogenerated stub
    }
}